### ISSUE TITLE
Image creation for CM311 (G12A, U212) is wrong, part sha1sum misplaced

### ISSUE THREAD

**Issue by fanTMT** [7Ji/ampack#2] opened 2024-10-03 07:45 UTC
Unpack and then repackage the img file.
-----------------------------------------------------------

λ ampack pack ./out/ ./out.img

Image version set to v2, alignment set to 4
Missing image item: super.PARTITION
CRC32 of image is 0xb582881f
Packed './out/' to './out.img'

λ ampack verify ./out.img

正在验证图像 './out.img'
Reading image => [00:00:00] ████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░       9/28      bootloader.VERIFY        Verify item content for bootloader is not sha1sum
Error: ImageError(IllegalVerify)

**Comment by fanTMT** [comment] 2024-10-03 07:50
Raw img
[🔴] × ampack verify ./output.img
正在验证图像 './output.img'
Item infos in raw image:
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| ID | type | item off | image off  |    size    | main type |   sub type   | verify | backup (id) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  0 |    0 |      0x0 |     0x3f40 |   0x154e00 |       USB |          DDR |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  1 |    0 |      0x0 |     0x3f40 |   0x154e00 |       USB |        UBOOT |      0 |     yes (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  2 |    0 |      0x0 |   0x158d40 |    0x14cb3 | PARTITION |     _aml_dtb |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  3 |    0 |      0x0 |   0x16d9f3 |       0x30 |    VERIFY |     _aml_dtb |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  4 |    0 |      0x0 |   0x16da24 |   0x154e00 |     UBOOT | aml_sdc_burn |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  5 |    0 |      0x0 |   0x2c2824 |      0x18a |       ini | aml_sdc_burn |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  6 |    0 |      0x0 |   0x2c29b0 |   0xb22800 | PARTITION |         boot |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  7 |    0 |      0x0 |   0xde51b0 |       0x30 |    VERIFY |         boot |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  8 |    0 |      0x0 |     0x3f40 |   0x154e00 | PARTITION |   bootloader |      1 |     yes (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
|  9 |    0 |      0x0 |   0xde51e0 |       0x30 |    VERIFY |   bootloader |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 10 |    0 |      0x0 |   0xde5210 |    0x80000 | PARTITION |         dtbo |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 11 |    0 |      0x0 |   0xe65210 |       0x30 |    VERIFY |         dtbo |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 12 |    0 |      0x0 |   0xe65240 |       0x40 | PARTITION |         logo |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 13 |    0 |      0x0 |   0xe65280 |       0x30 |    VERIFY |         logo |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 14 |    0 |      0x0 |   0x158d40 |    0x14cb3 |       dtb |       meson1 |      0 |     yes (2) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 15 |  254 |      0x0 |   0xe652b0 |   0x27a0c4 | PARTITION |          odm |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 16 |    0 |      0x0 |  0x10df374 |       0x30 |    VERIFY |          odm |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 17 |    0 |      0x0 |  0x10df3a4 |       0x9b |      conf |     platform |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 18 |  254 |      0x0 |  0x10df440 |  0x3548160 | PARTITION |      product |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 19 |    0 |      0x0 |  0x46275a0 |       0x30 |    VERIFY |      product |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 20 |    0 |      0x0 |  0x46275d0 |  0x10a5800 | PARTITION |     recovery |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 21 |    0 |      0x0 |  0x56ccdd0 |       0x30 |    VERIFY |     recovery |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 22 |  254 |      0x0 |  0x56cce00 | 0x389c6df0 | PARTITION |       system |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 23 |    0 |      0x0 | 0x3e093bf0 |       0x30 |    VERIFY |       system |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 24 |    0 |      0x0 | 0x3e093c20 |   0x200000 | PARTITION |       vbmeta |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 25 |    0 |      0x0 | 0x3e293c20 |       0x30 |    VERIFY |       vbmeta |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 26 |  254 |      0x0 | 0x3e293c50 |  0xf4253d4 | PARTITION |       vendor |      1 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
| 27 |    0 |      0x0 | 0x4d6b9024 |       0x30 |    VERIFY |       vendor |      0 |      no (0) |
+----+------+----------+------------+------------+-----------+--------------+--------+-------------+
Items in image:
+----+--------------+-----------+------------+------------------------------------------+
| ID |     stem     | extension |    size    |                 sha1sum                  |
+----+--------------+-----------+------------+------------------------------------------+
|  0 |          DDR |       USB |   0x154e00 |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
|  1 |        UBOOT |       USB |   0x154e00 |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
|  2 |     _aml_dtb | PARTITION |    0x14cb3 | 582e146fd9359f1a844496bf92a1f92ed5477c19 |
+----+--------------+-----------+------------+------------------------------------------+
|  3 | aml_sdc_burn |     UBOOT |   0x154e00 |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
|  4 | aml_sdc_burn |       ini |      0x18a |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
|  5 |         boot | PARTITION |   0xb22800 | a87e6a7b0cd2db760534e8ee7a2ab3ba6d1dc3d5 |
+----+--------------+-----------+------------+------------------------------------------+
|  6 |   bootloader | PARTITION |   0x154e00 | 2ed9a91fe2243b9f875043ffc99a67569a3fdeae |
+----+--------------+-----------+------------+------------------------------------------+
|  7 |         dtbo | PARTITION |    0x80000 | bc5012902b3b1b68f2bff3c4c8ea1e3e7e3d973b |
+----+--------------+-----------+------------+------------------------------------------+
|  8 |         logo | PARTITION |       0x40 | c41e11896ee27dc1f431991ad055a8935b9afe01 |
+----+--------------+-----------+------------+------------------------------------------+
|  9 |       meson1 |       dtb |    0x14cb3 |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
| 10 |          odm | PARTITION |   0x27a0c4 | 00ecd2a4584482202c45529650ece587ce83c1a5 |
+----+--------------+-----------+------------+------------------------------------------+
| 11 |     platform |      conf |       0x9b |                                     None |
+----+--------------+-----------+------------+------------------------------------------+
| 12 |      product | PARTITION |  0x3548160 | 2fc86ee355672fbbc144ee962c8a3b426e789cf1 |
+----+--------------+-----------+------------+------------------------------------------+
| 13 |     recovery | PARTITION |  0x10a5800 | e3e17ccb36811bbfd0f9d18cabef016b78cda70a |
+----+--------------+-----------+------------+------------------------------------------+
| 14 |       system | PARTITION | 0x389c6df0 | 3a1cbfb838e897bb47c7fa1504918c464ffcda0d |
+----+--------------+-----------+------------+------------------------------------------+
| 15 |       vbmeta | PARTITION |   0x200000 | 7d76d48d64d7ac5411d714a4bb83f37e3e5b8df6 |
+----+--------------+-----------+------------+------------------------------------------+
| 16 |       vendor | PARTITION |  0xf4253d4 | 0432294115a974e4fb451fb0a897c7721b439515 |
+----+--------------+-----------+------------+------------------------------------------+
正在验证图像 './output.img'

**Comment by 7Ji** [comment] 2024-10-03 10:02
1. Format your log with ``````, it looks messy and I can't follow what happened 
2. Don't paste translated result, it messed up with formatting
3. Share URL of your original image, and what you have done.

**Comment by fanTMT** [comment] 2024-10-03 12:36
是CM311-1a当贝桌面ROM unpack 后啥也不干，然后pack 
ampack verify 修改后的.img  验证不通过

**Comment by 7Ji** [comment] 2024-10-03 12:44
> Share URL of your original image, and what you have done.

**Comment by fanTMT** [comment] 2024-10-03 14:27
原始镜像 https://www.123684.com/s/fd7zVv-MtF7H?提取码:sdj4
ampack unpack cm311.img ./out/
ampack pack ./out/ ./out.img
ampack verify ./out.img

输出：
正在验证图像 './out.img'
Reading image => [00:00:00] ████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 9/28 bootloader.VERIFY Verify item content for bootloader is not sha1sum
Error: ImageError(IllegalVerify)

**Comment by fanTMT** [comment] 2024-10-03 15:08
![cmd](https://github.com/user-attachments/assets/d9f00714-d02e-4095-9186-62976a98d977)

**Comment by 7Ji** [comment] 2024-10-17 01:54
I just had time to work on this. The issue is that multiple image parts are essentially the same files, and the logic to save space by re-using verify checksums is not right.

```sh
> md5sum * | sort
30913b0850d8e8aaf15eed51d47c0eeb  dtbo.PARTITION
49eb05da222b692cc01dff7db586ff99  system.PARTITION
5fdd03d788293b5432c50a1bb44d38c0  aml_sdc_burn.UBOOT
5fdd03d788293b5432c50a1bb44d38c0  bootloader.PARTITION
5fdd03d788293b5432c50a1bb44d38c0  DDR.USB
5fdd03d788293b5432c50a1bb44d38c0  UBOOT.USB
64e84447bfdb1b3dab9b79c772f26181  aml_sdc_burn.ini
6ce598d038a6a0c85cb9843232df1901  platform.conf
b2d1236c286a3c0704224fe4105eca49  vbmeta.PARTITION
b5e7996e25495b52e8b416222baa5ced  logo.PARTITION
d185595313edef18e17b2b7f63c405c2  recovery.PARTITION
d4bc31872503ce32a843cb8126e74c5b  odm.PARTITION
e2d9d4de900411afe3c104ca19bb4da5  boot.PARTITION
ebadeab79dd243cd9399aaf481a632c3  product.PARTITION
ec204502bddc5b990c5a628b7e7c03c6  _aml_dtb.PARTITION
ec204502bddc5b990c5a628b7e7c03c6  meson1.dtb
f1a32d1f80d73fe7c74d2dcd566a79e1  vendor.PARTITION
```

**Comment by 7Ji** [comment] 2024-10-18 03:12
Closed by https://github.com/7Ji/ampack/commit/46066067b2b06c387df14243e301742644aa77a1

**Closed as completed by 7Ji** 2024-10-18 03:12 UTC
